name: WakaTime status update

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 */14 * *"

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: "main"
          COMMIT_MSG: "chore(): Updated with dev metrics"
          STATS_RANGE: "last_30_days"
